name: CI/CD Docker SRE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar pruebas
        run: pytest -v

  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Bandit
        run: pip install bandit

      - name: Ejecutar Bandit
        run: bandit -r app.py -ll

  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Construir imagen
        run: docker build -t docker-sre-taller:security .

      - name: Escanear imagen con Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: docker-sre-taller:security
          severity: CRITICAL,HIGH
          exit-code: "1"
          ignore-unfixed: true

  deploy:
    needs:
      - test
      - bandit
      - trivy
    runs-on: ubuntu-latest

    steps:
      - name: Desplegar en EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/docker-sre-taller
            git pull origin main
            COMPOSE_BAKE=false docker compose up -d --build
